### ISSUE TITLE
Livisi states are not shown correctly  in HA

### ISSUE THREAD

**Issue by Bikestuff** [planbnet/livisi_unofficial#172]
## System Information

version | core-2024.12.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.63-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.1
Stage | running
Available Repositories | 1489
Downloaded Repositories | 14

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 234.0 GB
disk_used | 46.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Advanced SSH & Web Terminal (19.0.0), File editor (5.8.0), Cloudflared (5.2.3), InfluxDB (5.0.1), MariaDB (2.7.1), Grafana (10.2.2), ESPHome Device Compiler (2024.11.3), Zigbee2MQTT (1.42.0-2), Mosquitto broker (6.4.1), Whisper (2.4.0), Piper (1.5.2), Bambu Lab P1 - Spaghetti Detection Server (1.0.0), Matter Server (6.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 13
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 30. November 2024 um 18:09
-- | --
current_recorder_run | 12. Dezember 2024 um 09:46
database_engine | mysql
database_version | 10.11.6

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Since a couple of days, (maybe since the last update?) I noticed that the states in Livisi are not correctly reflecting in HA
Livisi:
![image](https://github.com/user-attachments/assets/93a68bee-9694-45a4-9fe3-c82c4b4f3e6c)
HA:
![image](https://github.com/user-attachments/assets/6407a268-e1b3-4304-a1e2-b671975d93a0)

After reloading integration, all is shown correctly

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
2024-12-12 10:31:06.785 ERROR (MainThread) [custom_components.livisi] Unhandled error in WebSocket consumer handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1279, in close_connection
    await self.transfer_data_task
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1147, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/framing.py", line 71, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 769, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 539, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/livisi/livisi_websocket.py", line 67, in consumer_handler
    async for message in websocket:
    ...<16 lines>...
        on_data(event_data)
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 484, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 554, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received
2024-12-12 10:44:18.744 ERROR (MainThread) [custom_components.livisi] Unhandled error in WebSocket consumer handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1279, in close_connection
    await self.transfer_data_task
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1147, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/framing.py", line 71, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 769, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 539, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/livisi/livisi_websocket.py", line 67, in consumer_handler
    async for message in websocket:
    ...<16 lines>...
        on_data(event_data)
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 484, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 554, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received
```

**Comment by planbnet** [comment]
Can you please try to downgrade to [1.11.1](https://github.com/planbnet/livisi_unofficial/releases/tag/1.11.1) and see if the error persists? The new version fixed a lot of connection problems.

Another question: Do you have any Plugins (Medion, Hue) enabled in the controller?

**Comment by Bikestuff** [comment]
I don't use Philipps or Medion devices, I see the default plugins are installed.
Is it that what you mean?
![image](https://github.com/user-attachments/assets/10191855-09f2-4a0c-bb14-0387a4b214a7)

I'm not sur how to perform the downgrade?
Just unzip and replace the files in the given folder(s)?

Will the downgrade bring back unreachability issue of the SHC? That problem was gone in version 1.12.0

**Comment by Bikestuff** [comment]
There is no option to uninstall dedicated App Plugins:
![image](https://github.com/user-attachments/assets/98618fbf-efe8-43dc-a469-2c7e765027b1)

They all are beiing installed wit the device driver package "innogy Geräte", which is needed to use innogy devices.
![image](https://github.com/user-attachments/assets/d72697a6-3eb0-4c6c-a2c6-079624d30f3b)

**Comment by stefanhintermayr** [comment]
Now i had the same problem with the covers.
I'm in holidays, i click on the buttons, this will work, but the status didn't change.

I reload the integration, now the cover is closed.

**Comment by stefanhintermayr** [comment]
What do you mean with commits?

**Comment by planbnet** [comment]
There are changes in the code here which are not yet part of a release. Of everything workfs fine for me until tomorrow, I will release a new version which will hopefully fix all the disconnection problems people have (because it will simply try to reconnect every minue if the connection is lost)

**Comment by planbnet** [comment]
This should finally be fixed in 1.13.0

**Comment by Bikestuff** [comment]
Thx for caring, seem to be fixed until now

**Comment by Bikestuff** [comment]
Unfortunately, it did not change at all for me:

![Image](https://github.com/user-attachments/assets/95a3b1bf-7908-41f3-9bb0-c32a96778ec1)

**Logs:**
`2025-06-08 22:55:00.770 ERROR (MainThread) [custom_components.livisi] Unhandled error in WebSocket consumer handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1279, in close_connection
    await self.transfer_data_task
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
    message = await self.read_message()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
    frame = await self.read_frame(max_size)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 1147, in read_frame
    frame = await Frame.read(
            ^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/framing.py", line 71, in read
    data = await reader(2)
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 769, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/local/lib/python3.13/asyncio/streams.py", line 539, in _wait_for_data
    await self._waiter
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/livisi/livisi_websocket.py", line 74, in consumer_handler
    async for message in websocket:
    ...<28 lines>...
            LOGGER.error("Unhandled error in on_data", exc_info=e)
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 484, in __aiter__
    yield await self.recv()
          ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 554, in recv
    await self.ensure_open()
  File "/usr/local/lib/python3.13/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received
2025-06-08 22:55:00.780 WARNING (MainThread) [custom_components.livisi] WebSocket disconnected unexpectedly.
2025-06-08 22:55:04.977 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 101, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 394, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        pool_request.request
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_async/connection.py", line 124, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/onvif/managers.py", line 191, in _renew_or_restart_subscription
    await self._renew_subscription() or await self._restart_subscription()
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/onvif/managers.py", line 156, in _restart_subscription
    return await self._start()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/onvif/managers.py", line 300, in _start
    result = await events_service.CreatePullPointSubscription(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/zeep/proxy.py", line 64, in __call__
    return await self._proxy._binding.send_async(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/zeep/wsdl/bindings/soap.py", line 156, in send_async
    response = await client.transport.post_xml(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        options["address"], envelope, http_headers
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/zeep/transports.py", line 235, in post_xml
    response = await self.post(address, message, headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/onvif/wrappers.py", line 40, in _async_wrap_connection_error_retry
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/onvif/client.py", line 115, in post
    return await super().post(address, message, headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/zeep/transports.py", line 220, in post
    response = await self.client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1859, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<13 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1540, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1629, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1657, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1694, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_client.py", line 1730, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 393, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/httpx/_transports/default.py", line 118, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
2025-06-08 22:55:21.874 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)`
