### ISSUE TITLE
Attribute error - Livisi migration not successful

### ISSUE THREAD

**Issue by nanuyalailai** [planbnet/livisi_unofficial#173]
## System Information

version | core-2024.12.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.0
os_name | Linux
os_version | 6.6.51-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4853
Installed Version | 2.0.1
Stage | running
Available Repositories | 1489
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.0
-- | --
update_channel | stable
supervisor_version | supervisor-2024.11.4
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 28.5 GB
disk_used | 21.2 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Whisper (2.4.0), Piper (1.5.2), Samba share (12.3.2), File editor (5.8.0), Ecowitt HTTP Proxy (1.0.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 7
-- | --
resources | 8
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 23, 2024 at 20:19
-- | --
current_recorder_run | December 15, 2024 at 16:39
estimated_db_size | 1101.35 MiB
database_engine | sqlite
database_version | 3.45.3

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I get the following error log in HA:

Logger: homeassistant.config_entries
Source: config_entries.py:983
First occurred: 16:39:24 (2 occurrences)
Last logged: 16:39:24

Error migrating entry SHC Classic for livisi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/__init__.py", line 160, in async_migrate_entry
    config_entry.version = 2
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 468, in __setattr__
    raise AttributeError(
        f"{key} cannot be changed directly, use async_update_entry instead"
    )
AttributeError: version cannot be changed directly, use async_update_entry instead

### Reproduction steps

1. follow manua instructions
2. reload HA
3. check integration: now Livisi original is gone and custom is ther but with the above errors
...

### Debug logs

```text
2024-12-15 16:39:06.052 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration ha_fritzprofiles which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 16:39:06.054 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 16:39:06.056 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration livisi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 16:39:06.058 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration myenergi which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 16:39:06.060 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration elero which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 16:39:06.061 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration melcloud_custom which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-15 16:39:14.481 ERROR (SyncWorker_5) [custom_components.elero] The '7' channel is not taught to the 'AU00JPT5' transmitter.
2024-12-15 16:39:15.730 WARNING (ImportExecutor_0) [homeassistant.core] Config was used from myenergi, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'myenergi' custom integration
2024-12-15 16:39:24.031 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry SHC Classic for livisi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/__init__.py", line 160, in async_migrate_entry
    config_entry.version = 2
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 468, in __setattr__
    raise AttributeError(
        f"{key} cannot be changed directly, use async_update_entry instead"
    )
AttributeError: version cannot be changed directly, use async_update_entry instead
2024-12-15 16:39:24.201 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry SHC Classic for livisi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 983, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/__init__.py", line 160, in async_migrate_entry
    config_entry.version = 2
    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 468, in __setattr__
    raise AttributeError(
        f"{key} cannot be changed directly, use async_update_entry instead"
    )
AttributeError: version cannot be changed directly, use async_update_entry instead
```

**Comment by planbnet** [comment]
Seems like this was changed in a recent HA update.. I'll take a look

**Comment by planbnet** [comment]
This will  be fixed in the next release
