### ISSUE TITLE
PSD2 nicht mehr verfügbar wenn nicht als Licht deklariert

### ISSUE THREAD

**Issue by metaiiica** [planbnet/livisi_unofficial#80]
### System Health details

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:03:58 (2 occurrences)
Last logged: 17:06:15

[547090681152] Failed to turn on None
[546905561664] Failed to turn on None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/livisi/switch.py", line 86, in async_turn_on
    raise HomeAssistantError(f"Failed to turn on {self._attr_name}")
homeassistant.exceptions.HomeAssistantError: Failed to turn on None

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

wenn ein Zwischenstecker zB. in der Kategorie Entertainment oder andere eingeordnet ist und nicht unter Licht werden die Zwischenstecker als nicht verfügbar angezeigt. Unter 1.7.4 läuft wieder alles wie gewohnt.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```text
.
```

**Comment by metaiiica** [comment]
Ach ja, nutze SHC V1
