### ISSUE TITLE
Can't turn on or off switches after update.

### ISSUE THREAD

**Issue by marcel51090** [planbnet/livisi_unofficial#81]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

after the last update I can't turn on or of any switches.

I get the Error message:

![IMG_7157](https://github.com/planbnet/livisi_unofficial/assets/133398651/51b9a715-31fd-44a4-b072-e49657c0385b)

### Reproduction steps

1. restart livisi
2. restart livisi integration in home assistant
3. turn on/ off any livisi switch
...

### Debug logs

```Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:240
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:00:36 (2 occurrences)
Last logged: 12:14:05

[546852822848] Failed to turn on None
[547382106560] Failed to turn on None
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 240, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2279, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2316, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 962, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/livisi/switch.py", line 86, in async_turn_on
    raise HomeAssistantError(f"Failed to turn on {self._attr_name}")
homeassistant.exceptions.HomeAssistantError: Failed to turn on None

```

### Diagnostics dump

...

**Comment by metaiiica** [comment]
If you have 1.8.0, update to 1.8.1

solve your issue
