### ISSUE TITLE
keine Initialisierung der SHC1 nach Update

### ISSUE THREAD

**Issue by FJJT01** [planbnet/livisi_unofficial#84]
## System Information

version | core-2024.2.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.1
os_name | Linux
os_version | 6.1.63-haos-raspi
arch | aarch64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.34.0
Stage | running
Available Repositories | 1396
Downloaded Repositories | 16

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.5
-- | --
update_channel | stable
supervisor_version | supervisor-2024.01.1
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 58.0 GB
disk_used | 15.2 GB
healthy | true
supported | true
board | rpi4-64
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.0), Cloudflared (5.1.3), Signal Messenger (0.81.0), ArgonOne Active Linear Cooling (30a), Samba NAS (12.2.0-nas1), Advanced SSH & Web Terminal (17.1.0), TasmoAdmin (0.29.1), Silicon Labs Multiprotocol (2.4.4), Matter Server (5.1.2), Studio Code Server (5.15.0), Nextcloud Backup (0.17.7), ESPHome (2023.12.9)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 8
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 12. Februar 2024 um 19:05
-- | --
current_recorder_run | 20. Februar 2024 um 20:32
estimated_db_size | 688.92 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Nach dem Update auf 1.9.0 initialisiert die SHC1 leider wieder nicht. Downgrade direkt auf 1.8.1 stellt leider auch die Funktionität nicht wieder her, nur per Umweg über 1.7.4 auf 1.8.1 klappt wieder - ich bleibe nun erstmal auf dieser Version.

### Reproduction steps

1. Update auf 1.9.0
2. Reboot

### Debug logs

```text
-
```

**Comment by planbnet** [comment]
Kannst du Logs zur Verfügung stellen? Irgendwas bei der V1 scheint sich komplett anders zu verhalten als ich das erwarte.

**Comment by FJJT01** [comment]
2024-02-21 08:04:24.134 ERROR (MainThread) [custom_components.livisi] Unexpected error fetching Livisi devices data: 'list' object has no attribute 'add'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/coordinator.py", line 84, in _async_update_data
    return await self.async_get_devices()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/coordinator.py", line 113, in async_get_devices
    devices = await self.aiolivisi.async_get_devices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/livisi_connector.py", line 215, in async_get_devices
    ) = self.parse_messages(messages)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/livisi_connector.py", line 307, in parse_messages
    device_ids.add(source.replace("/device/", ""))
    ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'add'
2024-02-21 08:04:24.143 DEBUG (MainThread) [custom_components.livisi] Finished fetching Livisi devices data in 0.455 seconds (success: False)
2024-02-21 08:04:24.143 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SHC Classic for livisi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/livisi/__init__.py", line 52, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 278, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/config/custom_components/livisi/binary_sensor.py", line 47, in handle_coordinator_update
    for device in shc_devices:
TypeError: 'NoneType' object is not iterable

**Comment by planbnet** [comment]
Sorry!!! Fixed in 1.9.1
